### ISSUE TITLE
Readme lacks info about pulling the complete repository.

### ISSUE THREAD

**Issue by gpadd** [NanoWar/sublime-funk#1]
Add this code line: `git submodule update --init` to the [Readme.md](https://github.com/NanoWar/sublime-funk/blob/master/README.md) and explain that it's needed to get the funk-repo.
The command `git clone --recursive https://github.com/NanoWar/sublime-funk.git` would work as well, it pulls the submodules directly after the cloning is done, so no need to run the first command then.
However if you already have pulled the repo without --recursive, the first command is what you use.

**Comment by NanoWar** [comment]
Ok, thanks. Added!
